"""Clone isolated build hosts and insert actual source/generated bytes unchanged."""
import argparse
from pathlib import Path
import shutil

from common import HERE, sha, write_json

OLD = Path('/private/tmp/ui-program-transcription-20260912-dev')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--run', required=True, type=Path)
    parser.add_argument('--source', required=True, type=Path)
    parser.add_argument('--root', required=True, help='Fully qualified Kotlin Composable')
    parser.add_argument('--ets', type=Path, help='Actual generated ETS; may be supplied later')
    parser.add_argument('--component', help='Exported component when ETS does not contain @Entry')
    parser.add_argument('--android-test', type=Path, help='Optional source-specific instrumentation test template')
    parser.add_argument('--harmony-test', type=Path, help='Optional source-specific Hypium test template')
    args = parser.parse_args()
    run = args.run.resolve()
    run.mkdir(parents=True, exist_ok=False)
    source = args.source.resolve()
    android = run / 'android'
    shutil.copytree(HERE / 'templates/android', android)
    (android / 'MainActivity.kt.in').unlink()
    (android / 'ModifierOrderTest.kt.in').unlink()
    wrapper = OLD / 'android-build-05'
    shutil.copy2(wrapper / 'gradlew', android / 'gradlew')
    shutil.copytree(wrapper / 'gradle/wrapper', android / 'gradle/wrapper')
    code = android / 'app/src/main/java'
    code.mkdir(parents=True)
    shutil.copy2(source, code / 'Page.kt')
    (code / 'MainActivity.kt').write_text((HERE / 'templates/android/MainActivity.kt.in').read_text().replace('__ROOT__', args.root))
    if args.android_test:
        test_code = android / 'app/src/androidTest/java'
        test_code.mkdir(parents=True)
        shutil.copy2(args.android_test, test_code / 'FixtureTest.kt')
    target = run / 'harmony'
    seed = OLD / 'fixture-run-15/target'
    shutil.copytree(seed, target, ignore=shutil.ignore_patterns('build', '.hvigor', 'oh_modules', '.idea'))
    # The cloned UI is removed wholesale; only the actual new generated page is hosted.
    shutil.rmtree(target / 'entry/src/main/ets')
    shutil.rmtree(target / 'entry/src/test')
    shutil.rmtree(target / 'entry/src/ohosTest/ets')
    ability = target / 'entry/src/main/ets/entryability'
    ability.mkdir(parents=True)
    shutil.copy2(HERE / 'templates/harmony/EntryAbility.ets', ability / 'EntryAbility.ets')
    test = target / 'entry/src/ohosTest/ets/test'
    test.mkdir(parents=True)
    for name in ('Ability.test.ets', 'List.test.ets'):
        shutil.copy2(HERE / 'templates/harmony' / name, test / name)
    if args.harmony_test:
        shutil.copy2(args.harmony_test, test / 'Ability.test.ets')
    config = {'source': str(source), 'source_sha256': sha(source), 'root': args.root,
              'harmony_seed': str(seed), 'seed_profile_sha256': sha(seed / 'build-profile.json5'),
              'android_package': 'dev.ets.verification', 'harmony_bundle': 'com.joker.kit',
              'generated': {}, 'status': 'awaiting-generated-output'}
    write_json(run / 'inputs.json', config)
    if args.ets:
        from stage_generated import stage
        stage(run, args.ets, args.component)
    print(run)


if __name__ == '__main__':
    main()
