"""Finite type inventory for the single-JSON renderer, not the legacy translator."""

CONTROL_FAMILIES = {
    'row': ('Row', 'LazyRow'),
    'column': ('Column', 'LazyColumn'),
    'card': ('Card',),
    'material_item': ('ListItem', 'FilterChip', 'ExtendedFloatingActionButton'),
    'box': ('Box', 'BoxWithConstraints', 'Surface', 'AnimatedVisibility', 'AnimatedContent'),
    'refresh': ('PullToRefreshBox',),
    'pager': ('HorizontalPager', 'VerticalPager'),
    'overlay': ('AlertDialog', 'Dialog', 'ModalBottomSheet'),
    'constraint': ('ConstraintLayout',),
    'appbar': ('TopAppBar', 'CenterAlignedTopAppBar', 'LargeFlexibleTopAppBar', 'BottomAppBar'),
    'scaffold': ('Scaffold',),
    'button': ('Button', 'TextButton', 'OutlinedButton', 'IconButton', 'IconToggleButton',
               'FloatingActionButton', 'SmallFloatingActionButton'),
    'text': ('Text', 'BasicText', 'ClickableText'),
    'input': ('BasicTextField', 'TextField', 'OutlinedTextField'),
    'image': ('Image', 'Icon', 'AsyncImage'),
    'spacer': ('Spacer',),
    'selection': ('Checkbox', 'Switch', 'RadioButton'),
    'range': ('Slider',),
    'progress': ('LinearProgressIndicator', 'CircularProgressIndicator'),
    'divider': ('Divider', 'HorizontalDivider', 'VerticalDivider'),
    'internal': ('content', 'toolbar', 'ProgressRing'),
}
NATIVE_CONTAINERS = frozenset(
    name for family in ('row', 'column', 'card', 'material_item', 'box', 'refresh', 'pager', 'overlay', 'constraint', 'appbar', 'scaffold')
    for name in CONTROL_FAMILIES[family]
) | {'content', 'toolbar'}
from ui_migration.controls.registry import CONTROLS
NATIVE_CONTAINERS = NATIVE_CONTAINERS | CONTROLS.names
NATIVE_LEAVES = frozenset(
    name for family in ('text', 'input', 'image', 'spacer', 'selection', 'range', 'progress', 'divider')
    for name in CONTROL_FAMILIES[family]
) | {'ProgressRing'}
NATIVE_BUTTONS = frozenset(CONTROL_FAMILIES['button'])

# Each schema slot has a source boundary and a real consumer (or an explicit gap).
# A field count is not a count of all overloads, modifier orders, or framework defaults.
FIELD_AUDIT = {
    'layout.padding_dp': ('all', '条件', 'expand_ordered_layout_modifiers 保留纯常量 padding/size/width/height 嵌套；交织绘制/重复同轴尺寸阻断', 'page_snapshot_component_lines'),
    'layout.margin_dp': ('all', '条件', '运行测量/页面事实；Compose 没有通用 margin 参数', 'page_snapshot_component_lines'),
    'layout.layout_direction': ('all', '条件', '页面事实；CompositionLocal 的上下文解析未全覆盖', 'page_snapshot_component_lines'),
    'layout.z_index': ('all', '条件', 'zIndex 走 layoutRules；该字段来自运行/页面事实', 'page_snapshot_component_lines'),
    'layout.alignment': ('row column box refresh appbar', '条件', 'contentAlignment/horizontalAlignment/verticalAlignment; 枚举', 'page_snapshot_container_alignment_lines'),
    'layout.horizontal_arrangement': ('row', '条件', 'Arrangement + 常量 spacedBy', 'page_snapshot_container_alignment_lines'),
    'layout.vertical_arrangement': ('column', '条件', 'Arrangement + 常量 spacedBy', 'page_snapshot_container_alignment_lines'),
    'layout.aspect_ratio': ('all', '已实现', 'aspectRatio 常量；不猜动态表达式', 'page_snapshot_component_lines'),
    'layout.width_dp': ('all', '条件', 'width/size; 无显式值使用原生测量，不用参考 frame', 'page_snapshot_dimension_lines'),
    'layout.height_dp': ('all', '条件', 'height/size; 无显式值使用原生测量，不用参考 frame', 'page_snapshot_dimension_lines'),
    'surface.background': ('all', '条件', 'solid/null、水平/垂直 Clamp 渐变；未知端点/径向/图片背景阻断', 'page_snapshot_component_lines'),
    'surface.corner_radius_dp': ('all', '条件', '四角事实；AbsoluteRoundedCornerShape、统一圆角；方向未知的非对称 Start/End 阻断', 'page_snapshot_component_lines'),
    'surface.corner_sizes': ('all', '条件', '带单位四角：dp/px/percent；百分比依赖原生测量的较短边；方向未知的非对称 Start/End 未解析', 'page_snapshot_component_lines'),
    'surface.border': ('all', '条件', '统一 solid/dashed/dotted/none；单边、自定义 dash 阻断', 'page_snapshot_component_lines'),
    'surface.shadows': ('all', '近似', '单阴影且 spread=0；Android elevation 转换仍是近似；多阴影阻断', 'page_snapshot_component_lines'),
    'surface.alpha': ('all', '已实现', 'alpha 常量 0..1', 'page_snapshot_component_lines'),
    'surface.clip': ('all', '条件', '矩形/圆角；自定义 Path 未支持', 'page_snapshot_component_lines'),
    'typography.font_size_sp': ('text input', '条件', 'Text/TextStyle 常量或已解析主题；字体缩放由运行平台消费', 'page_snapshot_component_lines'),
    'typography.font_weight': ('text input', '条件', 'FontWeight 常量/已解析主题', 'page_snapshot_component_lines'),
    'typography.font_style': ('text input', '已实现', 'FontStyle.Normal/Italic; 未知值 unresolved', 'page_snapshot_component_lines'),
    'typography.font_family': ('text input', '条件', '仅已校验字体资产或声明的系统字体', 'load_page_font_faces / page_snapshot_component_lines'),
    'typography.letter_spacing_sp': ('text input', '已实现', 'letterSpacing 常量 sp；支持负数', 'page_snapshot_component_lines'),
    'typography.line_height_sp': ('text input', '条件', '常量/主题；自定义 LineHeightStyle、低于自然行高未证明等价', 'page_snapshot_component_lines'),
    'typography.include_font_padding': ('text', '条件', 'false 且 Center/None 明确行高组合；其他组合保留消费缺口', 'TypographyEmitter.emit'),
    'typography.line_height_alignment': ('text', '条件', 'Center + Trim.None + includeFontPadding=false；其他组合未证明', 'TypographyEmitter.emit'),
    'typography.line_height_trim': ('text', '条件', 'None 明确保留首尾行高；其他非默认组合未证明', 'TypographyEmitter.emit'),
    'typography.line_break': ('text', '条件', 'Simple/Heading/Paragraph 映射目标换行策略；CJK严格度与自定义配置未证明等价', 'TypographyEmitter.emit'),
    'typography.baseline_shift': ('text', '条件', '已验证字体资源的基线倍率；其他字体保留未解析', 'TypographyEmitter.emit'),
    'typography.text_align': ('text input', '已实现', 'Start/Center/End/Justify', 'page_snapshot_component_lines'),
    'typography.max_lines': ('text input', '条件', '正整数；TextInput 与多行 TextArea 不是同一控件', 'page_snapshot_component_lines'),
    'typography.overflow': ('text input', '条件', 'clip/ellipsis；visible 未支持并阻断；两类 ArkUI 签名分开', 'page_snapshot_component_lines'),
    'typography.color': ('text input button', '条件', '明确颜色或已解析主题；容器颜色需实际下传到文字', 'page_snapshot_component_lines'),
    'typography.decoration': ('text input', '已实现', 'none/underline/line_through', 'page_snapshot_component_lines'),
    'asset.resource': ('image', '条件', '本地资源或 AsyncImage HTTP(S)；无预览图回退', 'page_snapshot_component_lines'),
    'asset.sha256': ('image', '证据', '资源提取记录；格式转换后由资源 provenance 验证，不是绘制属性', 'build_target_phase_consumption_gate'),
    'asset.width_px': ('image', '未支持', '可记录源像素尺寸；单输入渲染必须有逻辑尺寸，不能直接按 px 布局', 'build_target_phase_consumption_gate'),
    'asset.height_px': ('image', '未支持', '可记录源像素尺寸；不能当作 dp 使用', 'build_target_phase_consumption_gate'),
    'asset.width_dp': ('image', '条件', '资源本征尺寸，不是控件硬宽度', 'page_snapshot_intrinsic_image_lines'),
    'asset.height_dp': ('image', '条件', '资源本征尺寸，不是控件硬高度', 'page_snapshot_intrinsic_image_lines'),
    'asset.content_scale': ('image', '条件', 'fit/crop/fill/inside/none; 未指定尺寸时需可验证本征测量', 'page_snapshot_intrinsic_image_lines / page_snapshot_component_lines'),
    'asset.tint': ('image', '条件', '显式 tint/ColorFilter.tint；仅支持当前颜色滤镜映射', 'page_snapshot_component_lines'),
    'transform.translation_x_dp': ('all', '条件', '运行/页面事实；源码 offset 单独走 layoutRules，混合变换阻断', 'page_snapshot_component_lines'),
    'transform.translation_y_dp': ('all', '条件', '运行/页面事实；源码 offset 单独走 layoutRules，混合变换阻断', 'page_snapshot_component_lines'),
    'transform.scale_x': ('all', '条件', 'scale 常量；graphicsLayer/自定义原点/顺序组合未支持', 'page_snapshot_component_lines'),
    'transform.scale_y': ('all', '条件', 'scale 常量；不推算未知表达式', 'page_snapshot_component_lines'),
    'transform.rotation_degrees': ('all', '条件', 'rotate 常量；默认中心原点', 'page_snapshot_component_lines'),
    'state.visible': ('all', '条件', '显式布尔页面状态；消失不占位，不等于完整动画状态机', 'page_snapshot_component_lines'),
    'state.refreshing': ('refresh', '条件', 'isRefreshing 固定布尔状态；Box 叠加原生 LoadingProgress，动画外观近似，不包含刷新业务回调', 'page_snapshot_component_lines'),
    'state.enabled': ('all', '已实现', '显式布尔优先于默认值；动态未知值不填 true', 'page_snapshot_component_lines'),
    'state.selected': ('selection', '条件', 'RadioButton 的明确选中态；不代表任意容器都有选中样式', 'page_snapshot_component_lines'),
    'state.checked': ('selection', '条件', 'Checkbox/Switch 的明确布尔状态；缺失或动态未解析阻断', 'page_snapshot_component_lines'),
    'state.clickable': ('all', '业务边界', '只记录入口元数据；UI 渲染不产生业务 onClick，另走 behavior contract', 'build_target_phase_consumption_gate'),
    'state.focusable': ('all', '条件', '固定布尔值映射 focusable；交互流仍需 behavior wiring', 'page_snapshot_component_lines'),
    'content.text': ('text input button', '条件', 'text/value/已解析资源；Button 文本在子 Text 实际消费', 'page_snapshot_component_lines'),
    'content.placeholder': ('input', '条件', '纯文字提示；复杂 slot/浮动 label 不等同 placeholder', 'page_snapshot_component_lines'),
    'content.content_description': ('all', '已实现', 'contentDescription; 显式 null 不设置', 'page_snapshot_component_lines'),
    'content.role': ('all', '证据', '用于页面语义匹配，不代表已实现对应业务', 'build_target_phase_consumption_gate'),
    'content.locale': ('text input', '未支持', '可存储/采集；未单独消费，非空时阻断', 'build_target_phase_consumption_gate'),
    'input.single_line': ('input', '已实现', '显式布尔；源码省略按 Compose 多行默认；TextInput/TextArea 原生分流', 'page_snapshot_component_lines'),
    'input.read_only': ('input', '条件', '显式布尔；禁止软键盘及内容修改，保留选中；API 20+', 'page_snapshot_component_lines'),
    'input.password': ('input', '条件', '标准 PasswordVisualTransformation/None；多行密码、自定义字符变换阻断', 'page_snapshot_component_lines'),
    'input.keyboard_type': ('input', '条件', 'Text/Number/Phone/Email/Uri/Decimal/Password/NumberPassword；不等同内容校验', 'page_snapshot_component_lines'),
    'input.ime_action': ('input', '条件', '键盘动作枚举；Previous/单行 None 阻断；业务提交回调另走 contract', 'page_snapshot_component_lines'),
    'typography.soft_wrap': ('text', '条件', '显式布尔；false 支持不含硬换行的单段文字，硬换行逐段渲染未支持', 'page_snapshot_component_lines'),
    'typography.min_lines': ('text input', '条件', '1 为原生默认；多行 Text 使用已验证字体运行时 metrics，复杂约束/输入框多行最低行数阻断', 'page_snapshot_component_lines'),
    'control.value': ('range progress', '条件', '明确 value/progress；不使用样例数值；UI 当前态不等同业务订阅', 'page_snapshot_component_lines'),
    'control.minimum': ('range progress', '条件', 'Slider valueRange 或明确默认 0；进度固定 0..1', 'page_snapshot_component_lines'),
    'control.maximum': ('range progress', '条件', 'Slider valueRange 或明确默认 1；上限必须大于下限', 'page_snapshot_component_lines'),
    'control.steps': ('range', '条件', '离散 steps 转 (max-min)/(steps+1)；连续型与小于平台最小步长阻断', 'page_snapshot_component_lines'),
    'control.active_color': ('progress divider refresh', '条件', '显式 color 常量或刷新指示器主题色，作用于轨迹/分隔线而非文字', 'page_snapshot_component_lines'),
    'control.inactive_color': ('progress refresh', '条件', '显式 trackColor 常量或刷新指示器主题背景', 'page_snapshot_component_lines'),
    'control.stroke_width_dp': ('progress divider', '条件', '常量 thickness/strokeWidth；分隔线默认1dp', 'page_snapshot_component_lines'),
}

FAMILY_BOUNDARIES = {
    'overlay': 'Material3 AlertDialog/Dialog/ModalBottomSheet selected UI and named slots in native modal layers; business callbacks and custom window policies remain explicit boundaries',
    'pager': 'Compose Foundation pager: resolved finite pages, initial index, Fill size, spacing, padding, cross-axis alignment, native swipe; custom fling/reverse/fixed-size unresolved',
    'material_item': 'Material3 ListItem named slots and FilterChip fixed-state layout; callbacks remain a business boundary',
    'row': '原生 Row；LazyRow 为展开后的滚动树，不包含惰性复用策略',
    'column': '原生 Column；LazyColumn 为展开后的滚动树',
    'card': 'Material Card 的 Column 内容布局、静态填充/圆角/裁剪；非零 elevation 仍需单独验证，不能删除子树',
    'box': 'Stack + 原有子树；BoxWithConstraints 限已解析约束表达式',
    'refresh': 'Box 内容子树、尺寸、weight、对齐，刷新指示器叠加而不挤动内容；固定 UI 状态，手势回调与自定义 indicator/state 另行接入',
    'constraint': 'RelativeContainer；只接受已实现的 anchor 关系，不猜坐标',
    'appbar': '当前小型栏骨架；导航/actions slot 和复杂 appbar 默认样式未全覆盖',
    'scaffold': '保留 topBar/content/bottomBar 槽位；内容 padding 消费原生测量栏高；浮动按钮/snackbar 定位未覆盖',
    'button': '已解析外观 + 子树；不能宣称完整 Material 默认主题/状态/业务',
    'text': '原生文字；ClickableText 仅 UI，富文本/点击范围未全覆盖',
    'input': 'TextInput/TextArea、密码/只读/键盘；Material decoration/复杂 slot/label/error 仍需专门映射',
    'image': '原生 Image；资源/本征测量受验证门禁约束',
    'spacer': 'Blank 或空 Stack，随父容器与 weight 选择',
    'selection': '原生 Checkbox/Toggle/Radio 状态；完整 Material colors/slots 未支持，不能宣称默认外观跨平台等价',
    'range': '明确数值/范围/离散步数的原生 Slider；连续型和自定义 thumb/track 阻断',
    'progress': '确定值的 Linear/Ring 进度；不把不确定进度变为固定0或演示百分比',
    'divider': '原生水平/垂直分隔线；颜色与粗细直接消费',
    'internal': '内部结构或已结构化 ProgressRing，不计入 Android 控件数量',
}
