import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { cpSync, copyFileSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');
assert.ok(process.argv[2], 'Pass a successful modules/run.mjs evidence directory');
const previous = JSON.parse(readFileSync(join(resolve(process.argv[2]), 'result.json'), 'utf8'));
assert.equal(previous.passed, true);
assert.ok(process.argv[3], 'Pass a successful inline/run.mjs evidence directory');
const inlineRun = resolve(process.argv[3]);
const inlineComparison = JSON.parse(readFileSync(join(inlineRun, 'runtime.json'), 'utf8'));
assert.deepEqual(inlineComparison.actual, inlineComparison.expected);
assert.ok(inlineComparison.actual.length > 0);
const generated = previous.output;
const sdk = '/Applications/DevEco-Studio.app/Contents';
const seed = process.env.KOTLIN_ETS_SDK_SEED ?? '/private/tmp/kotlin-ets-native-20260913-07/harmony';
const work = mkdtempSync('/private/tmp/kotlin-ets-modules-sdk-');
const host = join(work, 'harmony');
const hash = path => createHash('sha256').update(readFileSync(path)).digest('hex');
const inputs = [generated, previous.genericOutput].flatMap(directory => readdirSync(directory).map(name => ({
  name, path: join(directory, name), sha256: hash(join(directory, name)),
})));
const inlinePath = join(inlineRun, 'application.ets');
inputs.push({ name: 'Inline.ets', path: inlinePath, sha256: hash(inlinePath) });
assert.equal(new Set(inputs.map(input => input.name)).size, inputs.length);
function sourceHashes(directory) {
  return readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    const path = join(directory, entry.name);
    return entry.isDirectory() ? sourceHashes(path) : [{ path, sha256: hash(path) }];
  });
}
const manifest = { seed, generated, host, inputs, implementation: sourceHashes(join(root, 'src')), commands: [] };
assert.deepEqual(manifest.implementation, previous.implementation, 'Modules were generated by a different compiler revision');
manifest.sourceInputs = previous.sourceInputs;
for (const input of manifest.sourceInputs) assert.equal(hash(input.path), input.sha256, 'Kotlin source changed after generation');
const record = () => writeFileSync(join(work, 'manifest.json'), JSON.stringify(manifest, null, 2));
const env = { ...process.env, JAVA_HOME: join(sdk, 'jbr/Contents/Home'), DEVECO_SDK_HOME: join(sdk, 'sdk'),
  PATH: `${sdk}/tools/node/bin:${sdk}/tools/ohpm/bin:${process.env.PATH}` };
function run(label, command, args) {
  const result = spawnSync(command, args, { cwd: host, env, encoding: 'utf8', timeout: 600000, maxBuffer: 32 * 1024 * 1024 });
  writeFileSync(join(work, label + '.stdout'), result.stdout ?? '');
  writeFileSync(join(work, label + '.stderr'), result.stderr ?? '');
  manifest.commands.push({ label, command, args, status: result.status, error: result.error?.message });
  record();
  assert.equal(result.error, undefined);
  assert.equal(result.status, 0, result.stdout + result.stderr);
}
console.log(`SDK evidence: ${work}`);
record();
const excluded = new Set(['build', '.hvigor', 'oh_modules', '.idea', '.migration', '.git']);
cpSync(seed, host, { recursive: true, filter: path => !excluded.has(basename(path)) });
const ets = join(host, 'entry/src/main/ets');
rmSync(ets, { recursive: true, force: true });
for (const directory of ['pages', 'entryability', 'modules']) mkdirSync(join(ets, directory), { recursive: true });
copyFileSync(join(here, 'SdkIndex.ets'), join(ets, 'pages/Index.ets'));
copyFileSync(join(root, 'tests/language/SdkEntryAbility.ets'), join(ets, 'entryability/EntryAbility.ets'));
writeFileSync(join(host, 'entry/src/main/resources/base/profile/main_pages.json'), JSON.stringify({ src: ['pages/Index'] }));
for (const input of inputs) copyFileSync(input.path, join(ets, 'modules', input.name));
run('ohpm-install', join(sdk, 'tools/ohpm/bin/ohpm'), ['install']);
run('sdk-assemble', join(sdk, 'tools/hvigor/bin/hvigorw'),
  ['assembleHap', '--mode', 'module', '-p', 'module=entry@default', '-p', 'product=default', '--no-daemon']);
for (const input of inputs) {
  assert.equal(hash(input.path), input.sha256);
  assert.equal(hash(join(ets, 'modules', input.name)), input.sha256);
}
for (const source of manifest.implementation) assert.equal(hash(source.path), source.sha256);
for (const input of manifest.sourceInputs) assert.equal(hash(input.path), input.sha256);
const filesInfo = join(host, 'entry/build/default/cache/default/default@CompileArkTS/esmodule/debug/filesInfo.txt');
const records = readFileSync(filesInfo, 'utf8').split('\n');
manifest.compiledModules = inputs.map(input => {
  const record = records.find(line => line.includes(`/modules/${input.name.slice(0, -4)}.ts;`) && line.endsWith(';ets'));
  assert.ok(record, `Missing actual ETS SDK input: ${input.name}`);
  return record;
});
const abc = join(host, 'entry/build/default/intermediates/loader_out/default/ets/modules.abc');
manifest.abc = { path: abc, sha256: hash(abc) };
const outputs = join(host, 'entry/build/default/outputs/default');
manifest.haps = readdirSync(outputs).filter(name => name.endsWith('.hap')).map(name => ({
  path: join(outputs, name), sha256: hash(join(outputs, name)),
}));
assert.ok(manifest.haps.length > 0);
manifest.passed = true;
record();
console.log(`PASS actual ETS SDK: ${inputs.length} generated modules, generic imports and official inline output, unchanged bytes, HAP output`);
